sirius 6 adjustments (#118)
* build from s6 config, disable patching and testing for now

* workflow can not be empty, remove pull-request trigger instead

* remove template overwrite

* use OpenAPI generator for Python

* use snapshot api docs

* fix bug using old docs

* delete old api docs file

* Update sirius_api.py

Updated API Endpoints for S6

* Fixed double entry

* pass only api_client

* initial rewrite of SDK

* pass self to reset()

* Create test_login_and_account_api.py

* improved logging

* merge initial changes of clients and tests for s6

* Auto-Updated OpenAPI Clients

* Added first stages of testing

* job test

* Update test_login_and_account_api.py

* Update test_projects_api.py

* Create test_actuator_api.py

* Update test_info_api.py

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: me62did <hoffmann.m@uni-jena.de>
Co-authored-by: Jonas Emmert <63006948+joXemMx@users.noreply.github.com>

* general patches for R client to work

* Readme update for "Getting started"

* use assert after deleting the temp folders

* absolute directory paths

* Fixed typo in file name

* rework and update job tests

* s6 alpha api docs

* disable R manual rescue

* AutoUpdated (#59)

* Auto-Updated OpenAPI Clients

* update existing tests to new API version

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: joXemMx <jonas.em@t-online.de>

* add more tests

* add missing endpoints

* start testing features api

* full minimal test of compounds api

* add comment

* tidy up projects api test

* tidy up jobs api test

* final s6 api docs

* Auto-Updated OpenAPI Clients (#60)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* re-implement manual actuator shutdown

* improve actuator shutdown usage

* s6 specs including actuator shutdown

* Auto-Updated OpenAPI Clients (#61)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* final docs from martin

* updated tests for final build

* fixed final docs from martin

* Auto-Updated OpenAPI Clients (#63)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* tests and test-skeletons for databases api

* Added SearchableDatabases API shortcut

* add new stubs for R tests, test actuator api

* [R] fix api response in templates, fix lists with script

* [R] delete obsolete script, fix path in other

* [R] relative path

* Auto-Updated OpenAPI Clients (#64)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* [R] info api complete test

* [R] initial login and account api testing

* start feature api tests with full projectspace

* [Python] nearly finished features api tests

* [Python] add features api tests

* [R] possible template fix for api_client not being able to handle empty body

* [R] change to httr2 client template

* Auto-Updated OpenAPI Clients (#67)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* move to newest generator release, new API docs

* revert docs, keep generator

* config with nullable workerinfo version

* Auto-Updated OpenAPI Clients (#73)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* [R] updated projects_api tests

* [R] updated templates

* [Python] assert PS creation to ProjectInfo

* [R] adjusted api.mustache template

* [R] add test ImportPreprocessedData

* [R] add ImportMsRunData test (commented out)

* [R] completed projects api test stubs

* [R] add GetSignUpURL test

* [R] add CompoundsAPI tests

* use OpenAPI generator 7.5.0 SNAPSHOT

* Auto-Updated OpenAPI Clients (#76)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* [R] delete mustache files that were included into openapi generator

* [R] temporarily modify modelGeneric template until merged

* Auto-Updated OpenAPI Clients (#77)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* [R] try fixing toJSONString for nested enum models

* [R] corrected formatting

* Auto-Updated OpenAPI Clients (#79)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* update api-docs

* Auto-Updated OpenAPI Clients (#80)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* use stable generator for languages except R

* Auto-Updated OpenAPI Clients (#81)

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* [Python] re-enable tests where the API got fixed

* Update api docs

* Auto-Updated OpenAPI Clients

* Allow random port in Python SDK (#91)

* [Python] allow start on random port and to reattach to running SIRIUS

* [Python] allow start on random port and to reattach to running SIRIUS

* redo generation using port 8080 docs to enable coherent testing

* Auto-Updated OpenAPI Clients

* enable automatic api-doc grabbing again

* Auto-Updated OpenAPI Clients

* try do undo bug for files introduced after openapi generator 7.4.0

* Auto-Updated OpenAPI Clients

* fix bug where numeric objects are taken for enum objects

fixes following error:

Error: Argument 'txt' must be a JSON string, URL or file.
> traceback()
5: base::stop(..., call. = FALSE)
4: stop("Argument 'txt' must be a JSON string, URL or file.")
3: jsonlite::fromJSON(self$ilpTimeout$toJSON()) at sirius.R#277
2: self$formulaIdParams$toJSON() at job_submission.R#173
1: response$toJSON()

* Auto-Updated OpenAPI Clients

* fix if syntax error

* Auto-Updated OpenAPI Clients

* nullify whole class if class has only null values

* Auto-Updated OpenAPI Clients

* exchange %d with %f for numeric values

should fix following error:
> api_instance$GetAlignedFeatures("tomato")
[[1]]
Error in sprintf("\"ionMass\":\n            %d\n                    ",  :
  invalid format '%d'; use format %f, %e, %g or %a for numeric objects

* Auto-Updated OpenAPI Clients

* [Python] temporarily disable test_open_project_space

* [Python] enable test_get_connection_check

* [R] intermediate test update

* [Python] re-enable OpenProjectSpace

* [Python] remove check for "scores" folder

* fix json string error for GetJobConfigs()

reduces the wrong json string
"\"fallbackAdducts\":[\"c(\"[M + K]+\", \"[M - H]-\", \"[M + Na]+\", \"[M + H]+\")\"]"
to a correct
"\"fallbackAdducts\":[\"[M + K]+\", \"[M - H]-\", \"[M + Na]+\", \"[M + H]+\"]"

* Auto-Updated OpenAPI Clients

* [R] clean up CrateProjectSpace calls

* [Python] prepare test_get_traces

* [Python] remove time.sleep while assertion of results is turned off

* fix serialization faults and disable enum check bug in initialize

* [R] update test_jobs_api

* Auto-Updated OpenAPI Clients

* [R] add tests of denovo outputs for single aligned_feature_id

* [Python] adjust SDK restart service only to random port

* [R] initial sirius6 adjustment for R SDK

* [Python] adjust FeatureApi tests to new project space

* [R] add DeleteAlignedFeature test to FeaturesAPI

* [R] change api_client template to allow raw response if it is not valid json (GetSignUpURL)

* Auto-Updated OpenAPI Clients

* [R] move api_client template

* Auto-Updated OpenAPI Clients

* [R] catch ULR string responses more robust

* Auto-Updated OpenAPI Clients

* prepare automated test workflow pipeline

* add pull_request trigger to tests again

* adjust sirius download curl

* activate cache update

* fail on cache miss

* adjust R versions

* temporarily disable seps.lockpull.outcome

* enable steps.lockpull.outcome again

* manual sirius download for now, cache only available from master branch

* disable lockpull.outcome

* possible fix for HOME environment variable change

* install failing devtools dependencies beforehand

* try to unset DISPLAY variable causing: jakarta.servlet.ServletException: Handler dispatch failed: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.

* Rsirius installation independent of devtools

* temporary removal of RManualGeneration

* try unsetting DISPLAY by JAVA_TOOL_OPTIONS=-Djava.awt.headless=true

* fix RTests directory name

* make R tests independent of each other but dependent on RSirius install

* make python tests independent of each other but dependent on PySirius install and API start

* add API start dependency to R tests

* include minimal cyclic wait for job deletion to complete

* increase cyclic wait for job deletion to complete

* add always() to if dependencies of steps

* homogenize test workflows, checkout earlier in RTest

* add login in front of tests and as dependency for running tests

* login fail print

* fix boolean syntax

* add missing features_api tests

* extend delete_job spinwait

* test_files should allow stop_on_failure use

* hardcode s6 stable download, change R tesing workflow back to R CMD check

* create tests folder before moving tests

* remove login to debug

* enable login again

* correct file extension

* add testthat.R file

* disable features API test

* fix path to Rsirius folder

* path fix

* path fix

* add R example file

* add Python example file

* Auto-Updated OpenAPI Clients

* do not delete empty test stubs for test adjustments

* Auto-Updated OpenAPI Clients

* remove redundant test_get_frag_tree

* initial adjustments to 6.0.1

* initial adjustments to 6.0.1

* initial adjustments to 6.0.1

* Auto-Updated OpenAPI Clients

* Added stable docs only

* Auto-Updated OpenAPI Clients

* fix port auto discovery in python api and update docs (#117)

* Changed port and pid autodiscovery

* fixed check for sirius on path

* Added docstring

* Updated help, added convenience method connect_remote

Closes #115

* Minor refactoring

---------

Co-authored-by: Andrii Kovalov <andrii.kovalov@bright-giant.com>

* adjusted tests to stableDocOnly

* check environment for SIRIUS_EXE before checking PATH

* remove redundant sirius download

---------

Co-authored-by: MartinHoffmannJena <43675767+MartinHoffmannJena@users.noreply.github.com>
Co-authored-by: boeckergitlab <44767363+boeckergitlab@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: me62did <hoffmann.m@uni-jena.de>
Co-authored-by: MartinHoffmannJena <MartinHoffmannJena@users.noreply.github.com>
Co-authored-by: joXemMx <joXemMx@users.noreply.github.com>
Co-authored-by: andriikovalov <andrewsk@ukr.net>
Co-authored-by: Andrii Kovalov <andrii.kovalov@bright-giant.com>